AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-lambdas

  Sample SAM Template for sam-app-lambdas by rk

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
Resources:
  DynamoDBByRk2:
    Type: AWS::Serverless::SimpleTable
    Properties:
      Tags:
        rk: rk
      PrimaryKey:
        Name: id
        Type: String
      TableName: first-dynamo-table-by-rk-2
  SAMS3BucketByRK:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: "rk"
          Value: "rk"
      BucketName: "sam-cli-resource-bucket-by-rk-2"
      AccessControl: "PublicReadWrite"
  SAMCLIHelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        rk: rk
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        SAMCLIHelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sam-cli-hello-world
            Method: get
  SAMCLIDynamoDBReadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        rk: rk
      CodeUri: dynamo-db/
      Handler: app.dynamoDBReadHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDBByRk2
      Events:
        SAMCLIDynamoDBRead:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sam-cli-dynamo-db-read
            Method: get
  SAMCLIDynamoDBCreateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        rk: rk
      CodeUri: dynamo-db/
      Handler: app.dynamoDBCreateHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoDBByRk2
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDBByRk2
      Events:
        SAMCLIDynamoDBWrite:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sam-cli-dynamo-db-create
            Method: post
  SAMCLIDynamoDBUpdateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        rk: rk
      CodeUri: dynamo-db/
      Handler: app.dynamoDBUpdateHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDBByRk2
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoDBByRk2
      Events:
        SAMCLIDynamoDBUpdate:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sam-cli-dynamo-db-update
            Method: put
  SAMCLIDynamoDBDeleteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Tags:
        rk: rk
      CodeUri: dynamo-db/
      Handler: app.dynamoDBDeleteHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBByRk2
      Events:
        SAMCLIDynamoDBDelete:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sam-cli-dynamo-db-delete
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SAMCLIHelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sam-cli-hello-world/"
  SAMCLIHelloWorldFunction:
    Description: "SAM CLI based lambda function created by rishabh kalra"
    Value: !GetAtt SAMCLIHelloWorldFunction.Arn
  SAMCLIHelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function by rishabh kalra"
    Value: !GetAtt SAMCLIHelloWorldFunctionRole.Arn
